- 깨끗한 코드를 다루는 책에 오류 처리를 논하는 장이 있어 이상하게 여길 지도 모르겠다.
오류 처리는 프로그램에 반드시 필요한 요소 중 하나일 뿐이다.
입력이 이상하거나 디바이스가 실패할지도 모르기 때문이다.
간단히 말해, 뭔가 잘못될 가능성은 항상 존재한다.
뭔가 잘못되면 바로 잡을 책임은 바로 우리 프로그래머에게 있다.

- 깨끗한 코드와 오류처리는 확실히 연관성이 있다. 상당수 코드 기반은 전적으로 오류 처리 코드에 좌우된다. 여기서 좌우된다는 표현은 코드 기반이 오류만 처리한다는 의미가 아니다. **여기저기 흩어진 오류 처리 코드 때문에 실제 코드가 하는 일을 파악하기가 거의 불가능하다는 의미다.** 오류 처리는 중요하다. 하지만 오류 처리 코드로 인해 프로그램 논리를 이해하기 어려워진다면 깨끗한 코드라 부르기 어렵다.

- 이 장에서는 깨끗하고 튼튼한 코드에 한 걸음 더 다가가는 단계로 우아하고 고상하게 오류를 처리하는 기법과 고려 사항 몇 가지를 소개한다.

### 오류코드보다 예외를 사용하라

- 얼마 전까지만 해도 예외를 지원하지 않는 프로그래밍 언어가 많았다.
예외를 지원하지 않는 언어는 오류를 처리하고 보고하는 방법이 제한적이었다. 오류 플래그를 설정하거나 호출자에게 오류 코드를 반환하는 방법이 전부였다. 목록 7.1은 다음과 같은 방법을 보여준다.

목록 7-1. DeviceController.java
```java
public class DeviceController {
  ...
  public void sendShutDown(){
     DeviceHandle handle = getHandle(DEV1);
    //디바이스 상태를 점검한다.
    if (handle != DeviceHandle.INVALID){
    	//레코드 필드에 디바이스 상태를 저장한다.
        retrieveDeviceRecord(handle);
        // 디바이스가 일시정지 상태가 아니라면 종료한다.
        if (record.getStatus() != DEVICE_SUSPENDED){
            pauseDevice(handle);
            clearDeviceWorkQueue(handle);
            closeDevice(handle);
        } else {
        	logger.log(" Device suspende. Unable to shut down");
		} 
    } else {
       logger.log("Invalid handle for:" + DEV1.toString());
   }
  }
}
```
- 위와 같은 방법을 사용하면 호출자 코드가 복잡해진다. 함수를 호출한 즉시 오류를 확인해야 하기 때문이다. 불행히도 이 단계는 잊어버리기 쉽다. 그래서 오류가 발생하면 예외를 던지는 편이 낫다. 그러면 호출자 코드가 더 깔끔해진다. **논리가 오류처리 코드와 뒤섞이지 않으니까.**

목록 7-2는 오류를 발견하면 예외를 던지는 코드다.

```java
목록 7-2 DeviceController.java(예외 사용)

public class DeviceController{
...
  public void sendShutDown(){
     try {
        tryToShutDown();
    } catch (DeviceShutDownError e){
        logger.log(e);
    }
 }
 
 private void tryToShutDown() throws DeviceShutDownEerror {
    DeviceHandle handle - getHandle(DEV1);
    DeviceRecord record = retriveDeviceRecord(handle);
    
    pauseDevice(handle);
    clearDeviceWorkQueue(handle);
    closeDevice(handle);
 }
 
 public DeviceHandle getHandle(DeviceID id) {
   ...
   throw new DeviceShutDownError("Invalid handle for " + id.toString());
 }
}
```

- 코드가 확실히 깨끗해지지 않았는가! 단순히 보기만 좋아지지 않았다.
코드 품질도 나아졌다. 앞서 뒤섞였던 개념, 즉 디바이스를 종료하는 알고리즘과 오류를 처리하는 알고리즘을 분리했기 때문이다. 이제는 각 개념을 독립적으로 살펴보고 이해할 수 있다.

### Try-Catch-Finally 문부터 작성하라.
- 예외에서 프로그램 안에다 **범위를 작성한다**는 사실은 매우 흥미롭다.
try-catch-finally 문에서 try 블록에 들어가는 코드를 실행하면 어느 시점에서든 실행이 중단된 후 catch 블록으로 넘어갈 수 있다.

- 어떤 면에서 try 블록은 트랜잭션과 비슷하다. try 블록에서 무슨 일이 생기던 catch 블록은 프로그램 상태를 일관성 있게 유지해야 한다. 그러므로 예외가 발생할 코드를 짤 때는 try-catch-finally 문으로 시작하는 편이 낫다. 그러면 try블록에서 무슨 일이 생기던지 호출자가 기대하는 상태를 정의하기 쉬워진다.

- 예제를 살펴보자. 파일을 열어 직렬화된 객체 몇 개를 읽어 들이는 코드가 필요하다.
다음은 파일이 없으면 예외를 던지는지 알아보는 단위테스트다.

```java

@Test(expected=StorageException.class)
public void retrieveSectionShouldThrowOnInvalidFileName(){
  sectionStore.retrieveSection("invalid-file");
}
```

단위 테스트에 맞춰 다음 코드를 구현했다.
```java
public List<RecordedGrip> retrieveSection(String sectionName){
//실제로 구현할 때까지 비어 있는 더미를 반환한다.
return new ArrayList<RecordedGrip>();
}
```

그런데 코드가 예외를 던지지 않으므로 단위 테스트는 실패한다.
잘못된 파일 접근을 시도하게 구현을 변경하자.
아래 코드는 예외를 던진다.
```java
public List<RecordedGrip> retrieveSection(String sectionName){
  try {
    FileInputStream stream = new FileInputStream(sectionName)
 } catch(Exception e){
   throw new StorageException("retrieval error", e);
} return new ArrayList<RecordedGrip>();
}
```
- 코드가 예외를 던지므로 이제는 테스트가 성공한다. 이 시점에서 리팩터링이 가능하다.
- catch 블록에서 예외 유형을 좁혀 실제로 FileInputStream 생성자가 던지는 FileNotFoundException을 잡아낸다. 

```java
public List<RecordedGrip> retrieveSection(String sectionName){
  try {
    FileInputStream stream = new FileInputStream(sectionName);
    stream.close();
 } catch(FileNotFoundException e){
   throw new StorageException("retrieval error", e);
} return new ArrayList<RecordedGrip>();
}

```

- try-catch 구조로 범위를 정의했으므로 TDD를 사용해 필요한 나머지 논리를 추가한다. 
나머지 논리는 FileInputStream을 생성하는 코드와 close 호출문 사이에 넣으며 오류나 예외가 전혀 발생하지 않는다고 가정한다.

- 먼저 강제로 예외를 일으키는 테스트 케이스를 작성한 후 테스트를 통과하게 코드를 작성하는 방법을 권장한다.
그러면 자연스럽게 try 블록의 트랜잭션 범위부터 구현하게 되므로 범위 내에서 트랜잭션 본질을 유지하기 쉬워진다.


##### 참고자료
클린코드 - 로버트 C.마틴 지음 ,  7장 - 오류처리
